version: "3.8"

services:
  redis-dms-auth:
    image: redis:7
    command:
      [
        "redis-server",
        "--requirepass", "MatKhauSieuManh123!123456asdasd@4324",
        "--user", "nam", "on", ">MatKhauSieuManh123!123456asdasd@4324", "allcommands", "allkeys"
      ]
    # ✅ Expose port Redis ra ngoài (nếu bạn cần truy cập từ host hoặc service khác)
    ports:
      - "6390:6379"   # Redis port
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - htdo_net

  dms-auth:
    image: harbor.hyundaitaydo.com.vn:8015/htdo_dms-auth-service/dms_htv:${IMAGE_TAG}
    deploy:
        replicas: 2
        placement:
            constraints:
                - node.role == manager
        resources:
              limits:
                  cpus: "1.0"
                  memory: 1024M
              reservations:
                  memory: 1024M
    ports:
      - "3001:3000"
    volumes:
      - /home/htdo/htdo/dms-auth-service/.env:/app/.env
    environment:
      NODE_ENV: production
    networks:
      - htdo_net
networks:
    htdo_net:
        external: true
